services:
  - type: web
    name: treka-backend
    env: node
    buildCommand: npm install
    startCommand: node api/server.js
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false 